### ISSUE TITLE
--tweets saves 0 tweets.

### ISSUE THREAD

**Issue by NSAKEY** [GuerrillaWarfare/Pronto#1]
I can run "pronto --tweets _nsakey" and the following happens:
 
>[INFO]: Collecting _nsakey's Tweets from page 1
>[SNIPPED FOR LENGTH]
>[INFO]: Collecting _nsakey's Tweets from page 71
>
>
>[INFO]: Wrote 0 of _nsakey's tweet links to disk.
>
>Traceback (most recent call last):
>  File "/usr/local/bin/pronto", line 107, in <module>
>    main(sys.argv[1])
>  File "/usr/local/bin/pronto", line 83, in main
>    operations.CollectStatuses(arg)
>  File "/usr/local/bin/Pronto/core/libs/twitter.py", line 137, in CollectStatuses
>    storage.database.WriteTweetLinksToFile(IDN, TwitterHandle, sl)
>  File "/usr/local/bin/Pronto/core/libs/storage.py", line 93, in WriteTweetLinksToFile
>    with open(tweetspath, 'a+') as file:
>IOError: [Errno 20] Not a directory: '_nsakey/1536924265__nsakey.tweet.links'

The directory wasn't made automatically, so I decided to make it myself and re-run the script. This is what happened:

>[INFO]: Collected 72 pages of tweets from _nsakey
>[INFO]: Wrote 0 of _nsakey's tweet links to disk.

"1536924265__nsakey.tweet.links" does get created, but it's a 0 byte file.

**Comment by GuerrillaWarfare** [comment]
The problem i found when running the tweet collection process is that a username MUST be in it's case-sensitive form or it will not work.

case-sensitive meaning the EXACT way you found it on twitter.

Try this instead:
./pronto.py --tweets _NSAKEY
